services:
  postgres:
    image: postgres:16
    restart: on-failure
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: alphapolocaldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d alphapolocaldb || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: on-failure
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network
  redis:
    image: redis:latest
    container_name: alphapo_redis
    restart: unless-stopped
    ports:
      - "6385:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 123456
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservices-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: alphapo_redis_commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOST: redis     
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
      REDIS_URL: redis://redis:123456@redis:6379
    
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - microservices-network



  app:
    build: .
    container_name: alphapo_app
    ports:
      - "5000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/alphapolocaldb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - microservices-network


volumes:
  postgres_data:
  redis_data:

networks:
  microservices-network:
    
